spring.application.name=dayflowj
server.address=127.0.0.1
spring.datasource.url=jdbc:h2:file:./data/dayflowj
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
